### ISSUE TITLE
App Graphics

### ISSUE THREAD

**Issue by neynah** [anherrera/budget#19]
Hi @anherrera,

Here's my first shot at some logo/icon mock-ups for your app. I'll see if I can think of other concepts ideas this week. Let me know if you've got any ideas! :)

![budget-app-mockup1](https://cloud.githubusercontent.com/assets/855341/11108410/7ca932e2-889b-11e5-9385-f3462eb31c62.png)

**Comment by anherrera** [comment]
I love em! :) If I had to pick it'd be the purple one, that's my favorite color.

**Comment by neynah** [comment]
Great! I'll probably tweak these a bit then submit a PR with the files to be included in your Sandstorm package.

**Comment by ocdtrekkie** [comment]
Sandcats like the color purple too. :)

**Comment by neynah** [comment]
@anherrera Do you think either of these are an improvement? :) If so, let's go with one of them. I can do a PR today.
![budget-app-mockup3](https://cloud.githubusercontent.com/assets/855341/14576746/f6b1e0ca-0320-11e6-8707-f2c7ec08ffc1.png)

**Comment by anherrera** [comment]
I like the one with the lighter background better. These look great!

**Comment by neynah** [comment]
Closed by #23
